cart/urls.py
from django.urls import path
from .views import CartPage
from cart.views import AddToCart, DelFromCart, ChangeAmount, MakeOrder, DetailOrder
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    path('detail/', CartPage.as_view(), name='cart_page'),
    path('add_to_cart/<pk>/', AddToCart.as_view(), name='add_to_cart_page'),
    path('del_from_cart/<pk><int:amount>/', DelFromCart.as_view(), name='del_from_cart_page'),
    path('changeamount/<pk>/', ChangeAmount.as_view(), name='change_amount_page'),
    path('makeorder/', MakeOrder.as_view(), name='make_order_page'),
    path('order/<pk>/', DetailOrder.as_view(), name='detail_order_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/admin/', admin.site.urls),
    path('', include('products.urls')),
    path('auth/', include('users.urls')),
    path('cart/', include('cart.urls')),
]

products/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from .views import *

app_name = 'products'

urlpatterns = [
    path('', MainPage.as_view(), name='main_page'),
    path('<slug>/', MainGroup.as_view(), name='main_group_page'),
    path('p/<slug>/', PrimaryGroup.as_view(), name='primary_group_page'),
    path('product/<pk>/', ProductPage.as_view(), name='detail_product_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import Login, Logout, Register, Vklogin, VkloginSuccess, VkloginRegister, AuthWithVk, UserPage

app_name = 'users'

urlpatterns = [
    path('login/', Login.as_view(), name='login_page'),
    path('logout/', Logout.as_view(), name='logout_page'),
    path('register/', Register.as_view(), name='register_page'),
    path('vkauth/', Vklogin.as_view(), name='vkauth_page'),
    path('vksuccessauth', VkloginSuccess.as_view(), name='success_page_auth'),
    path('registervk/', VkloginRegister.as_view(), name='vk_register_page'),
    path('vklogin/', AuthWithVk.as_view(), name='vk_login_page'),
    path('detail/', UserPage.as_view(), name='user_page'),
]

templates/base.html
<!doctype html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
		  content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://use.fontawesome.com/3a413b96b6.js"></script>
	{% load static %}
	<link rel="stylesheet" href="{% static 'main.css' %}">
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<header>
		<div class="container-fluid shadow" id="top-bar">
			<div class="row">
				<div class="col-2">
					<a href="{% url 'products:main_page' %}" id='logo'>E-Commerce</a>
				</div>
				<div class="col-3"></div>
				<div class="col-5">
					{% if not user.is_authenticated %}
						<form action="{% url 'users:login_page' %}" id="authform_before" method="POST">
								{% csrf_token %}
								{{auth_form.email}}
								{{auth_form.password}}
								<div class="submit-class">
									<input type="submit" value="Войти" class='submit-blank'>
									<div id="verticalline"></div>
									<a href="{% url 'users:register_page' %}" class='submit-blank'>Регистрация</a> 
								</div>
								<div class="vk_auth">
									<a href="{% url 'users:vkauth_page' %}">
										<img src="{% static 'vk.png' %}" alt="Авторизация через Вконтакте" height="25px" width="25px">
									</a>
								</div>
						</form>
					{% else %}
					<div id="authform-after">
						{% if user.first_name is not None %}
							<a href="{% url 'users:user_page' %}">{{user.first_name}} {{user.second_name}}</a>
						{% else %}
							<a href="{% url 'users:user_page' %}">{{user.email}}</a>
						{% endif%}
						<a href="{% url 'users:logout_page' %}">Выход</a>
					</div>
					{% endif %}
				</div>
				<div class="col-2">
					<!-- CART -->
						{% if cart.len == 0  %}
						<a href="" id='cart-link'>
							Корзина <i class="fa fa-shopping-cart fa-2" aria-hidden="true"></i>
						</a>
						{% else %}
						<a href="{% url 'cart:cart_page' %}" id='cart-link'>
							<p>Товаров: {{cart.len}}</p>
							<p>{{cart.get_sum_price}} Р</p>
						</a>
						{% endif %}
				</div>
			</div>
		</div>
	</header>
	<div class="container-fluid" id='main'>
		<div class="row">
			<div class="col-2" id='nav'>
				{% block menu %}{% endblock %}
			</div>
			<div class="col-10">
				{% block content %}{% endblock %}
			</div>
		</div>
	</div>
</body>
</html>