cart/urls.py
from django.urls import path
from .views import CartPage
from cart.views import AddToCart, DelFromCart, ChangeAmount, MakeOrder, DetailOrder
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    path('detail/', CartPage.as_view(), name='cart_page'),
    path('add_to_cart/<pk>/', AddToCart.as_view(), name='add_to_cart_page'),
    path('del_from_cart/<pk><int:amount>/', DelFromCart.as_view(), name='del_from_cart_page'),
    path('changeamount/<pk>/', ChangeAmount.as_view(), name='change_amount_page'),
    path('makeorder/', MakeOrder.as_view(), name='make_order_page'),
    path('order/<pk>/', DetailOrder.as_view(), name='detail_order_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/admin/', admin.site.urls),
    path('', include('products.urls')),
    path('auth/', include('users.urls')),
    path('cart/', include('cart.urls')),
]

products/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from .views import *

app_name = 'products'

urlpatterns = [
    path('', MainPage.as_view(), name='main_page'),
    path('<slug>/', MainGroup.as_view(), name='main_group_page'),
    path('p/<slug>/', PrimaryGroup.as_view(), name='primary_group_page'),
    path('product/<pk>/', ProductPage.as_view(), name='detail_product_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.utils.text import slugify
from django.shortcuts import reverse
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


class MainCategories(models.Model):
    name = models.CharField(max_length=1024, unique=True)
    date_making = models.DateField(auto_now_add=True)
    slug = models.SlugField(blank=True, max_length=1024)
    have_primary = models.BooleanField(default=False)

    REQUIRED_FIELDS = [
        'name',
    ]

    class Meta:
        indexes = [
            models.Index(fields=['name'])
        ]

    def get_absolute_url(self):
        return reverse('products:main_group_page', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        # logging.info(f'Created MAIN CATEGORY: [{self.name}]')
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class PrimaryCategories(models.Model):
    name = models.CharField(max_length=1024, unique=True)
    date_making = models.DateField(auto_now_add=True)
    slug = models.SlugField(blank=True, max_length=1024)
    main_group = models.ForeignKey('MainCategories', null=True, on_delete=models.CASCADE, related_name='primary_group')

    REQUIRED_FIELDS = [
        'name',
    ]

    class Meta:
        indexes = [
            models.Index(fields=['name'])
        ]

    def get_absolute_url(self):
        return reverse('products:primary_group_page', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        # logging.info(f'Created PRIMARY CATEGORY : [{self.name}]')
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Products(models.Model):
    main_category = models.ForeignKey('MainCategories', on_delete=models.CASCADE, related_name='products', null=True)
    primary_category = models.ForeignKey('PrimaryCategories', on_delete=models.CASCADE, related_name='products',
                                         null=True)
    name = models.CharField(max_length=1024, unique=True)
    price = models.IntegerField()
    description = models.TextField()
    main_characteristic = models.TextField()
    image = ProcessedImageField(upload_to='products_images/',
                                format='PNG',
                                options={'quality': 100},
                                default='products_images/no_image.png')
    slug = models.SlugField(blank=True, max_length=1024)
    image_url = models.TextField(null=True)
    date_adding = models.DateField(auto_now_add=True)

    REQUIRED_FIELDS = [
        'name',
        'price',
        'description',
    ]

    class Meta:
        indexes = [
            models.Index(fields=['name'])
        ]

    def get_absolute_url(self):
        return reverse('products:detail_product_page', args=[self.pk])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        # logging.info(f'Created PRIMARY CATEGORY PRODUCT: [{self.name}]')
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .models import Products


class AddToCart(forms.ModelForm):
    class Meta:
        model = Products

        fields = {}

class DelFromCart(forms.ModelForm):
    class Meta:
        model = Products

        fields = {}

products/views.py
from django.shortcuts import render, redirect
from django.views import generic
import logging
from .models import *
from cart.cart import *
from users.forms import AuthForm
from .forms import AddToCart


class MainPage(generic.View):
    def get(self, request):
        context = {
            'main_categories': MainCategories.objects.all(),
            'cart': Cart(request),
            'auth_form': AuthForm(),
            'new_products': Products.objects.order_by('date_adding')[:18]
        }
        return render(request, 'products/main_page.html', context)


class MainGroup(generic.View):
    def get(self, request, slug):
        try:
            main_group = MainCategories.objects.get(slug=slug)
        except MainCategories.DoesNotExist:
            logging.info(slug)
        main_context = {
            'cart': Cart(request),
            'auth_form': AuthForm(),
        }
        if main_group.have_primary:
            context = {
                'primary_categories': main_group.primary_group.all(),
                'new_products': Products.objects.filter(primary_category__in=main_group.primary_group.all()).order_by('date_adding')[:12]
            }
            main_context.update(context)
            return render(request, 'products/primary_page.html', main_context)
        else:
            context = {
                'products': Products.objects.filter(main_category=main_group),
                'cart_form': AddToCart(),
            }
            main_context.update(context)
            return render(request, 'products/products.html', main_context)


class PrimaryGroup(generic.View):
    def get(self, request, slug):
        primary_group = PrimaryCategories.objects.get(slug=slug)
        main_context = {
            'cart': Cart(request),
            'auth_form': AuthForm(),
            'products': primary_group.products.exclude(image_url=None),
        }
        return render(request, 'products/products.html', main_context)


class ProductPage(generic.DetailView):
    model = Products
    template_name = 'products/detail_product.html'
    context_object_name = 'product'

products/templates/products/detail_product.html
{% extends 'base.html' %}

{% block content %}
Пусто пока :()
{% endblock %}

products/templates/products/main_page.html
{% extends 'base.html' %}

{% block menu %}
<nav>
    <ul>
        {% for category in main_categories %}
            {% if category.have_primary %}
                <li class='category-name'><a href="{{category.get_absolute_url}}">{{category.name}} &gt;</a></li>
                <div class="underline"></div>
            {% else %}
                <li class='category-name'><a href="{{category.get_absolute_url}}">{{category.name}}</a></li>
                <div class="underline"></div>
            {% endif %}
        {% endfor %}
    </ul>
</nav>
<div id="verticalline"></div>
{% endblock %}

{% block content %}
<p>Новые поступления:</p>
<div class="underline"></div>
<p></p>
    <div class="row">
        {% for product in new_products %}
            <div class="col-2">
                <div class="product-mini shadow">
                   <div class="product-mini-name">
                        <a href="{{product.get_absolute_url}}">{{product.name}}</a>
                   </div>
                    <a href="{{product.get_absolute_url}}">
                            {% if product.image_url is not None %}
                                <img src="{{product.image_url}}" alt="{{product.name}}" align="center">
                            {% else %}
                                <img src="{{product.image.url}}" alt="{{product.name}}" height="100" width="100" align="center">
                            {% endif %}
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

products/templates/products/primary_page.html
{% extends 'base.html' %}

{% block menu %}
<nav>
    <ul>
        {% for category in primary_categories %}
        	<li><a href="{% url 'products:primary_group_page' category.slug %}">{{category.name}}</a></li>
        {% endfor %}
    </ul>
</nav>
<div id="verticalline"></div>
{% endblock %}

{% block content %}
	<p>Новые поступления:</p>
	<div class="underline"></div>
	<p></p>
    <div class="row">
        {% for product in new_products %}
            <div class="col-2">
                <div class="product-mini shadow">
                   <div class="product-mini-name">
                        <a href="{{product.get_absolute_url}}">{{product.name}}</a>
                   </div>
                    <a href="{{product.get_absolute_url}}">
                            {% if product.image_url is not None %}
                                <img src="{{product.image_url}}" alt="{{product.name}}" align="center" class='img-fluid'>
                            {% else %}
                                <img src="{{product.image.url}}" alt="{{product.name}}" height="100" width="100" class='img-fluid'>
                            {% endif %}
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

products/templates/products/products.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
	{% for product in products %}
	    <div class="row shadow" id="product">
	    	<div class="col-1" id='product_image'>
	    		{% if product.image_url is not None %}
	    			<img src="{{product.image_url}}" alt="{{product.name}}">
	    		{% else %}
					<img src="{{product.image.url}}" alt="{{product.name}}" height="100" width="100">
	    		{% endif %}
	    	</div>
	    	<div class="col-10">
	    		<span>{{product.name}}</span>
	    		<span>{{product.description}}</span>
	    	</div>
	    	<div class="col-1">
				<form action="{% url 'cart:add_to_cart_page' product.pk %}" method="Post">
					{% csrf_token %}
					{% if product.price == 0 %}
						<span>Нет в наличии</span>
						<input type="submit" value="В корзину" disabled class='buy-product'>
					{% else %}
						<span>{{product.price}}</span>
						<input type="submit" value="В корзину" class='buy-product'>
					{% endif %}
				</form>
	    	</div>
	    </div>
	{% endfor %}
</div>
{% endblock %}